apiVersion: v1
kind: Service
metadata:
  name: nodeserver-service-loadbalance
spec:
  selector:
    app: nodeserver
  type: LoadBalancer
  ports:
  - name: nodeserver-service-loadbalance
    port: 3000
    protocol: TCP
